---
title: "2. SiteData preparation_Cinput_Canada"
author: "Dr. Chih-Yu Hung"
date: "2024-07-04"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("setup.R")
Cinput    <- read.csv("Input/CropC_Daycent/CinputsAtEcodprov_19Oct2023.csv") #C input proportion not crop specific
Ecodc     <- read.csv("Input/CropC_Daycent/ecodcinputbycrop.csv") # C input crop specific 
EcoP      <- read.csv("Input/CropC_Daycent/EcoProvTexSites.csv") # C ini values
load("Input/Data_Weather.RData")     

```



```{r }
## Prepare 11y  average data to predict SOC
#C input Crop specific
TotalCinput_Crop <- Ecodc %>%
  filter(YEAR %in% c(2002:2012)) %>%
  mutate(Cinput_ha = CInput_withRootExudates_t /     # t / ha for each record
                        Corrected_Area) %>% 
  group_by(ECODISTRIC, Province_ID, CROPS) %>%
  summarise(Cinput = mean(Cinput_ha,  na.rm = TRUE),        # un-weighted
            AREA = mean(Corrected_Area, na.rm = TRUE),     # avg ha per year
            ) 

#join the weather data
SiteData_Crop <- TotalCinput_Crop %>%
  left_join(Weather, by = c("ECODISTRIC" = "Ecodistrict" ))%>%
  left_join(EcoP, by = c("ECODISTRIC", "Province_ID" = "PROVINCE")) %>%
  filter(!TEXCAT == "na") %>%
  group_by(ECODISTRIC, Province_ID, CROPS) %>%
  mutate(AREA = AREA * totalHec/sum(totalHec)) %>% #determine area based on soil texture
  select(ECODISTRIC, Province_ID, CROPS, Cinput, AREA, MAP, MAT, MPE, TEXCAT, CARB30, Frac = PERCECO)

#Save data
summary(SiteData_Crop) #Cinput, AREA, MAP, MAT, MPE, CARB: 2.062, 31.97, 520.8, 2.592, 542.9, 6365.
#write_rds(SiteData_Crop, file="Input/Canada Cinput_2002-2012.rds")

```