---
title: "4. SOC change_Tillage_Canada"
author: "Dr. Chih-Yu Hung"
date: "2025-08-16"
output: html_document
---

## SOC change due to tillage

The data is directly from our inventory. I didn't do any new calculation
The unit in the input file is kt CO22 and ha. 


```{r data input}
#Wrangle data
source("setup.R")

tillage <- read.csv("Input/Tillage EF_wide_wrangle.csv")

# Generate a sequence of years from 1990 to 2022
years <- seq(1990, 2022)

# Create an empty vector to store the column names
column_names <- character(length(years) * 2)

# Assign names for CO2e and Act.Area columns for each year
for (i in seq_along(years)) {
  column_names[(i - 1) * 2 + 1] <- paste0("CO2e_", years[i])
  column_names[(i - 1) * 2 + 2] <- paste0("Act.Area_", years[i])
}

# Assign the generated column names to the respective columns
colnames(tillage)[-(1:2)] <- column_names


tillage_long <- pivot_longer(tillage, 
                             cols = -c(Province, Practices), 
                             names_to = c(".value", "Year"), 
                             names_pattern = "(CO2e|Act\\.Area)_(\\d{4})")
```


## Check the tillage trend between 1990 and 2022

I want to know the proportion that has been converted to NT in 1990-2003 and every year after

The total crop area data is from Cinput data. I sum all area up. 

```{r}
#Obtain total crop area between 1990 and 2022
denom  <- read.csv("Input/CropC_Daycent/ecodcinputbycrop.csv") %>% # Total crop area in Canada
          select(Province_ID, YEAR, Corrected_Area) %>%
          filter(YEAR %in% c(1990:2022)) %>%
          group_by(Province_ID, YEAR) %>%
          summarise(Area = sum(Corrected_Area, na.rm = TRUE), .groups = "drop") %>%
          transmute(Province = Province_ID,
            Year = as.character(YEAR),
            Area) %>%
          mutate(Province = ifelse(Province == "NF", "NL", Province))

#know the total CT-NT conversion area between 1990-2022 
# Annual conversion area (keep 1990–2022 as-is)
num <- tillage_long %>%
  filter(Practices == "Conventional to Zero-till",
         between(Year, 1990, 2022)) %>%
  group_by(Province, Year) %>%
  summarise(Conv_to_NT = sum(Act.Area, na.rm = TRUE), .groups = "drop") %>%
  mutate(Year = as.character(Year))

#Calculate the trend to see the proportion
Tillage_trend <- denom %>%
  left_join(num, by = c("Province", "Year")) %>%
  mutate(Region = ifelse(Province %in% c("NB", "NL", "NS", "PE"), "AT", Province)) %>%
  group_by(Region, Year) %>%
  summarise(Conv_to_NT = sum (Conv_to_NT), 
            Area = sum (Area)) %>%
  mutate(Prop = Conv_to_NT / Area)

#convert the table
pick_year <- function(df, yr, ha_name, prop_name) {
  df %>%
    filter(Year == as.character(yr)) %>%
    select(Region, ha = Conv_to_NT, prop = Prop) %>%
    rename(!!ha_name := ha, !!prop_name := prop)
}

nt_2022 <- pick_year(Tillage_trend,  2022, "NT_2022_ha", "NT_2022_prop")
nt_1990 <- pick_year(Tillage_trend,  1990, "NT_1990_ha", "NT_1990_prop")  # note: 1990

Tillage_comp <- full_join(nt_2022, nt_1990, by = "Region") %>%
                mutate(Diff = NT_2022_ha - NT_1990_ha)


#keep 2022 and 2002 data only (2002 used to represent 1990 to compare with US data)
Tillage_trean_CA <- Tillage_trend %>%
  group_by(Year) %>%
  summarise(Crop_Area = sum (Area),
            CTNT = sum(Conv_to_NT)) %>%
  mutate(Prop = CTNT/Crop_Area)

```



```{r}
SOC_tillage <- tillage_long %>%
  filter(Practices == "Conventional to Zero-till" &
         years %in% c(2018:2022)) %>%
  mutate(SOC = CO2e / 44 * 12 * 10^6) %>% # Convert CO2e to C and from kt to kg 
  group_by(Province, Practices, Year) %>%
  summarise(SOC = sum(SOC), 
            Act.Area = sum(Act.Area)) %>%
  left_join(denom, by = c("Province", "Year")) # join the total crop area data


# Take average for Maritime regions
SOC_tillage_region <- SOC_tillage %>%
  mutate(Region = ifelse(Province %in% c("NB", "NL", "NS", "PE"), "AT", Province)) %>%
  group_by(Region) %>%
  summarize(SOC_change_rate = -sum(SOC)/sum(Area)) %>% # positive to be align with Open LCA data
  left_join(Tillage_comp, by = "Region")

# Write the data frame
summary(SOC_tillage_region) #SOC rate: 17.110, NT_2022_prop 0.17964, NT_1990_prop 0.015627, Diff 459203
write.csv(SOC_tillage_region, "Output/4. SOC_Tillage_EF_Canada.csv", row.names = FALSE)

```