---
title: "4. SOC change_Tillage_US"
author: "Dr. Chih-Yu Hung"
date: "2025-08-16"
output: html_document
---

```{r setup, include=FALSE}

source("setup.R")

Area_age <- read_csv(us_outputs("5_US Tillage area.csv"))

         
#To know the proportion of NT in 1990
Area_1990 <- Area_age %>%
         filter(year_conv == 1990 & year_eval == 2022) %>%
         select(STATE, NT_1990_ha = area)

#Area data, no need to use county data as the change is based on state
#Need to use total agri area as the tillage practice include all crops
Area <- read_csv(us_outputs("3.3_Area_County_Crop_reconciled.csv")) %>%
   filter(DOUBLE == "N") %>%                      #remove double crop area
   group_by(STATE, YEAR) %>%
   summarise(Area_sum = sum(AREA))


#Cenus NT area data
Census <- read_csv(us_outputs("../Inputs/Tillage area_Census.csv")) %>% #acres
          mutate(NT_2022_prop = NT_2022/(NT_2022 + RT_2022 + CT_2022),  #1990 NT area proportion in 2022 total area
                 NT_2022_ha = NT_2022 * 0.404686,                       #convert to ha
                 STATE = toupper(full))  %>%                    
          left_join(Area_1990, by = "STATE") %>%
          mutate(NT_1990_prop = NT_1990_ha / (NT_2012 + RT_2012 + CT_2012),  #1990 NT area proportion in 2012 total area
                 Diff = NT_2022_ha - NT_1990_ha) %>%
          select(STATE,NT_2022_ha, NT_2022_prop, NT_1990_ha, NT_1990_prop, Diff)  
          
```


```{r cars}
#DeltaSOC calculation

deltaSOC <- Area_age %>%
  mutate(SOCchange_US_em = 1436.812 * exp(-0.068*age), # US average
         SOCchange_US_sa = 720.79   * exp(-0.028*age), # US saturation
         SOCchange_CA_mo = 131.1 * exp(-0.02517*age), # CA estimate
         SOCchange_CA_Chang = 1014.9 * exp(-0.081*age), # Chang from Canada's studies
         Totalchange_US_em = SOCchange_US_em * area,
         Totalchange_US_sa = SOCchange_US_sa * area,
         Totalchange_CA_mo = SOCchange_CA_mo * area,
         Totalchange_CA_Chang = SOCchange_CA_Chang * area) %>%
  group_by(STATE, year_eval) %>%
  summarise(
    Totalchange_sum_US = sum(Totalchange_US_em, na.rm = TRUE),
    #Avgchange_US = Totalchange_sum_US,
    Totalchange_sum_US_SA = sum(Totalchange_US_sa, na.rm = TRUE),
    Totalchange_sum_CA = sum(Totalchange_CA_mo, na.rm = TRUE),
    #Avgchange_CA = Totalchange_sum_CA,
    Totalchange_sum_CA_Chang = sum(Totalchange_CA_Chang, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  left_join(Area, by = c("STATE", "year_eval" = "YEAR")) %>%   #add total agr area in 2018-2022
  mutate(SOC_change_rate_US = Totalchange_sum_US / Area_sum,
         SOC_change_rate_US_SA = Totalchange_sum_US_SA / Area_sum,
         SOC_change_rate_CA = Totalchange_sum_CA / Area_sum,
         SOC_change_rate_CA_Chang = Totalchange_sum_CA_Chang / Area_sum) %>%
  group_by(STATE) %>%                                          #take the average for 2018-2022
  summarise(
    SOC_change_rate_US = mean(SOC_change_rate_US),
    SOC_change_rate_US_Saturation = mean(SOC_change_rate_US_SA),
    SOC_change_rate_CA = mean(SOC_change_rate_CA),
    SOC_change_rate_CA_Chang = mean(SOC_change_rate_CA_Chang)) %>%         # Actually same to county data
  left_join(Census, by = "STATE")                   # to compare the CTNT trend

summary(deltaSOC) #SOC_US, 64.307, SOC_CA 13.081, SOC_Chang 37.87 ,NT_2022_prop 0.35700, NT_1990_prop 0.049220
write.csv(deltaSOC, "Output/4. SOC_Tillage_EF_US.csv", row.names = FALSE)

```

